config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:index,:create] 
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :title, :body, :author
  acts_as_tree order: 'created_at DESC'
def to_digraph_label
	title
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def index
	@comments = Comment.hash_tree
end
def new
	@comment = Comment.new(parent_id: params[:parent_id])
end
def create
	if params[:comment][:parent_id].to_i > 0
		parent = Comment.find_by_id(params[:comment].delete(:parent_id))
		@comment = parent.children.build(comment_params)
	else
	@comment = Comment.new(comment_params)
    end
    if @comment.save
    	flash[:success] = 'your comment was successfully added'
    	redirect_to root_url
    else
    	render 'new'
    end
end
private
def comment_params
	params.require(:comment).permit(:title,:body,:author)
	
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
	def comments_tree_for(comments)
		comments.map do |comment, nested_comments|
			render(comment) + (nested_comments.size > 0 ? content_tag(:div, comments_tree_for(nested_comments). class: "replies") :nil)
		end.join.html_safe
	end
end
end

app/views/comments/_comment.html.erb
<div class="well">
	<h2><%= comment.title %></h2>
	<p class="text-muted"><%= comment.root? ? "Started by" : "Replied by" %> <strong><%= comment.author %></strong> on
    <%= l(comment.created_at, format: '%B, %d %Y %H:%M:%S') %></p>

	<blockquote>
		<p><%= comment.body %></p>
	</blockquote>
	<% from_reply_form ||= nil %>
	<% unless from_reply_form %>
	<% if comment.leaf? %>
	<small class="text-muted">There are no replies yet - be the first one to reply!</small>
	<% end %>
	<P><%= link_to 'reply', new_comment_path(comment.id) %></P>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
<% if @comment.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@comment.errors.count, "error") %>prohibited this comment from being saved:</h2>
<ul>
	<% @comment.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
</div>
	<% end %>

<%= f.hidden_field :parent_id %>
<div class="form-group">
	<%= f.label :title %>
	<%= f.text_field :title, class: 'form-control' %>
</div>
<div class="from-group">
	<%= f.label :author %>
	<%= f.text_field :author, class: 'form-control', required: true %>
</div>
<div class="form-group">
	<%= f.label :body %>
	<%= f.text_area :body, class: 'form-control', required: true %>
</div>
<%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/comments/index.html.erb
<div class="jumbotron">
	<div class="container">
		<h1>Join the discussion</h1>
		<p>Click the button below to start a new thread:</p>
		<p>
			<%= link_to "Add new topic", new_comment_path, class: 'btn btn-primary btn-lg' %>
		</p>
	</div>
</div>
<%= render @comments %>
<%= comments_tree_for @comments %>

app/views/comments/new.html.erb
<h1>New comment</h1>
<% if @comment.parent %>
<%= render 'comment', comment: @comment.parent, from_reply_form: true %>
<% end %>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CommentApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>">
<button type="button" class="close" data-dismiss="alert">&times;</button>
<%= value %>
</div>
<% end %>	
</div>
<div class="container">
<%= yield %>
</div>
</body>
</html>